[package]
name = "ag-cli"
version.workspace = true
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
libc.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[dev-dependencies]
tempfile.workspace = true
