[package]
name = "agentty"
version.workspace = true
authors.workspace = true
edition.workspace = true
description.workspace = true
repository.workspace = true
homepage.workspace = true

[[bin]]
name = "agentty"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
libc.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[dev-dependencies]
mockall.workspace = true
tempfile.workspace = true
